CREATE TABLE orders(id bigint generated by default as identity, status varchar(255));
CREATE TABLE orders_date(order_id bigint not null, status varchar(255), date_created date default current_date);
CREATE TABLE order_product(quantity integer not null, order_id bigint not null, product_id bigint not null);
